server:
  port: 8080
spring:
  datasource:
    username: root
    password: root
    #创建数据库连接，连接到springboot数据库
    url: jdbc:mariadb://localhost:3306/websocket?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
